config/routes.rb
AuthDemo::Application.routes.draw do
  resource :session, only: [:create, :destroy, :new]
  resource :user, only: [:create, :new, :show] do
    resource :counter, only: [:update]
  end

  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'

  root 'static_pages#home'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    # no user with given username
    return nil if user.nil?

    # check user's password
    user.password_digest.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def current_user
    # fetches the user we've logged in as
    return nil if self.session[:session_token].nil?
    @user ||= User.find_by(session_token: self.session[:session_token])
  end

  def log_in!(user)
    # force other clients to log out by regenerating token
    user.reset_session_token!
    # log this client in
    self.session[:session_token] = user.session_token
  end

  def log_out!
    self.session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  def update
    current_user.counter = params[:user][:counter]
    current_user.save!
    redirect_to user_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # signs a user in
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      # no user with the given name!
      render :new
    else
      # sign the user in
      log_in!(@user)
      redirect_to user_url
    end
  end

  def destroy
    # sign a user out
    log_out!
    redirect_to new_session_url
  end

  def new
    # presents a login form
    render :new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		render :home
	end

	def contact
		render :contact
	end

	def about
		render :about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    # sign up the user
    @user = User.new(user_params)
    if @user.save
      # redirect them to the new user's show page
      log_in!(@user)
      redirect_to user_url
    else
      # input didn't pass validation; re-render sign up form.
      render :new
    end
  end

  def new
    # present form for signup
    @user = User.new # dummy user object
    render :new
  end

  def show
    # show the user's details (just their username)
    if current_user.nil?
      # let them log in
      redirect_to new_session_url
      return
    end

    @user = current_user
    render :show
  end

  protected
  def user_params
    self.params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>



<html>
<head>
  <title>AuthDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
<div class="container-fluid">
<ul class="nav navbar-nav">
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    My account
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
   <li><%= link_to('My profile', user_url(current_user)) if logged_in? %></li>
   <li><%= link_to('Log out', session_url, method: :delete) if logged_in? %></li>
  </ul>
</div>
<% unless logged_in? %>
   <li><%= link_to 'sign in!', new_session_url %></li>
   <li><%= link_to 'or sign up!', new_user_url %></li>
 <% end %>  
   <li><%= link_to 'home', static_pages_home_url %></li>
   <li><%= link_to 'about', static_pages_about_url %></li>
   <li><%= link_to 'contact us', static_pages_contact_url %></li>
</ul>
</div>
</nav>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-6">
        <h1>About us.</h1>
    </div>
    <div class="col-md-6">
      <h1><small>  We get it.</small></h1>
      <p>Just because you live in a tree doesn't mean you get to keep all of the money that grows on it.</p>
    </div>
  </div>

  <div class="row">
    <h1 style="text-align:center">Meet the gang.</h1>
  </div>
  <br>

  <div class="row text-center">
    <div class="col-md-3">
      <img src="<%= image_path 'panda1.jpg' %>" alt="first panda" class="img-circle img-responsive">
      <h2>Damian Kunde DDS</h2>
      <p>DDS meaning doctorate in deal seeking.  It was Damian's vision that brought embarrassmentpon to life.</p>
    </div>  

    <div class="col-md-3">
      <img src="<%= image_path 'panda2.jpg' %>" alt="second panda" class="img-circle img-responsive">
      <h2>Ubaldo Weber</h2>
      <p><%= Faker::Lorem.paragraph %></p>
    </div>

    <div class="col-md-3">
      <img src="<%= image_path 'panda3.jpg' %>" alt="third panda" class="img-circle img-responsive">
      <h2>Travon Cassin</h2>
      <p><%= Faker::Lorem.paragraph %></p>
    </div>

    <div class="col-md-3">
      <img src="<%= image_path 'monkey.png' %>" alt="monkey and dog" class="img-circle img-responsive">
      <h2>Ms. Elaina Okuneva<br><small>(pictured left)</small></h2>
      <p><%= Faker::Lorem.paragraph %></p>
    </div>  
  </div>
</div>

app/views/static_pages/contact.html.erb
<style>
  tbody>tr:nth-of-type(odd) {
    background-color: #337ab7;

  }
</style>
<h1>Contact us.</h1>
<div class="row">
  <div class="col-md-6">

    <div class="form-group">
      <label for="full_name">Your full name</label>
      <input class="form-control" id="full_name" type="text">
    </div>

    <div class="form-group">
      <label for="email">Your email</label>
      <input class="form-control" id="email" type="text">
    </div>

    <div class="form-group">
      <label for="inquiry">Your inquiry</label>
      <textarea class="form-control" id="inquiry"></textarea>
    </div>

    <div class="form-group">
      <label for="tos">By checking the box below you agree that you 1) are a panda and 2) have a legitimate inquiry; pranksters and cross-species coupon extremists will be prosecuted to the fullest extent of the law.</label>
      <input type="checkbox" class="form-control" id="tos">
    </div>

    <input type="button" class="btn btn-primary" value="Send!">
  </div>

  <div class="col-md-6">
    <table class="table table_striped">
      <thead>
        <tr><th>Staff Name</th><th>Number</th></tr>
      </thead>
      <tbody>
        <tr><td>Damian Kunde DDS</td><td>242-969-1028</td></tr>
        <tr><td>Ubaldo Weber</td><td>201-120-0510</td></tr>
        <tr><td>Travon Cassin</td><td>929-578-4734</td></tr>
        <tr><td>Ms. Elaina Okuneva</td><td>973-113-2248</td></tr>
      </tbody>
    </table>    
  </div>
</div>

app/views/static_pages/home.html.erb
<style>
 img {
  display:block;
  margin:auto;
 }

</style>
<div class="jumbotron">
  <div class="row">
    <div class="col-md-4 text-center col-md-offset-1">
      <h1>Embarrassmentpon</h1>
    </div>
  </div>
</div>
<div class="row">

  <div id="home-carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#home-carousel" data-slide-to="0" class="active"></li>
      <li data-target="#home-carousel" data-slide-to="1"></li>
      <li data-target="#home-carousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner col-md-4" role="listbox">
      <div class="item active">
        <img src="<%= image_path 'panda.jpg' %>" alt="an eating panda" class="img-rounded img-responsive">
        <div class="carousel-caption">
          <h1>Hey</h1>
        </div>
      </div>
      <div class="item">
        <img src="<%= image_path 'coupon.jpg' %>" alt="coupon" class="img-rounded img-responsive">
        <div class="carousel-caption" style="color:black">
          <h1>WE find these</h1>
        </div>
      </div>
      <div class="item">
       <div class="carousel-caption" style="color:blue">
          <h1>So YOU can do more of this</h1>
        </div>
        <img src="<%= image_path 'relaxing_panda.jpg' %>" alt="laying down panda" class="img-rounded img-responsive">
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#home-carousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#home-carousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<br>
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= "#{Faker::Lorem.words(3).join(' ')}.  " %><small><%= Faker::Lorem.sentence %></small></h1>
    <p><%= Faker::Lorem.paragraph %></p>
  </div>  
</div>
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= "#{Faker::Lorem.words(3).join(' ')}.  " %><small><%= Faker::Lorem.sentence %></small></h1>
    <p><%= Faker::Lorem.paragraph %></p>
  </div>  
</div>
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= "#{Faker::Lorem.words(3).join(' ')}.  " %><small><%= Faker::Lorem.sentence %></small></h1>
    <p><%= Faker::Lorem.paragraph %></p>
  </div>  
</div>
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= "#{Faker::Lorem.words(3).join(' ')}.  " %><small><%= Faker::Lorem.sentence %></small></h1>
    <p><%= Faker::Lorem.paragraph %></p>
  </div>  
</div>
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= "#{Faker::Lorem.words(3).join(' ')}.  " %><small><%= Faker::Lorem.sentence %></small></h1>
    <p><%= Faker::Lorem.paragraph %></p>
  </div>  
</div>
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= "#{Faker::Lorem.words(3).join(' ')}.  " %><small><%= Faker::Lorem.sentence %></small></h1>
    <p><%= Faker::Lorem.paragraph %></p>
  </div>  
</div>

app/views/users/new.html.erb
<div class="row">
<div class="col-xs-4 col-xs-offset-1">
<h1>Sign up!</h1>

<ul>
  <% @user.errors.full_messages.each do |err_msg| %>
    <li><%= err_msg %></li>
  <% end %>
</ul>

<form action="/user" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  
  <div class="form-group">
    <label for="user_username">Username</label>
    <input
      class="form-control"
      type="text"
      name="user[username]"
      id="user_username"
      value="<%= @user.username %>">
  </div>
  <br>

  <div class="form-group">
    <label for="user_password">Password</label>
    <input class="form-control" type="password" name="user[password]" id="user_password">
  </div>
  <br>

  <input class="btn btn-primary" type="submit" value="Create User!">
</form>
</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, <%= @user.username %></p>

<p>Current Counter Value: <%= @user.counter %></p>

<form action="/user/counter" method="POST">
  <input type="hidden" name="_method" value="PUT">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="user_counter">New Counter Value</label>
  <input type="number" name="user[counter]" id="user_counter">

  <input type="submit" value="Update Counter!">
</form>

<form action="/session" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="submit" value="Logout!">
</form>